[tool.poetry]
name = "sureflap-api"
version = "4.2.1"
license = "Apache-2.0"
description = "SureFlap API is a simple, yet powerful RESTful API for products from Sure Petcare"
authors = ["Fabian Eulitz <dev@sustineo.de>"]
repository = "https://github.com/fabieu/sureflap-api"
keywords = ["Sureflap", "Sure Petcare", "REST", "API"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
cachetools = "^5.3.2"
fastapi = "^0.105.0"
uvicorn = "^0.23.2"
requests = "^2.31.0"
dynaconf = "^3.2.4"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
vermin = "^1.6.0"
autopep8 = "^1.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
